version: "4.37"

services:
  pastebin:
    build:
      context: .
    image: judyas/pastebin_app:1.0.0
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: