services:
  parser:
    build:
      context: ./parser
      dockerfile: Dockerfile
    image: parser:${PARSER_IMAGE_TAG}
#    scale: 2
    depends_on:
      - master
      - redis
    environment:
      PARSER_SERVER_PORT: ${PARSER_SERVER_PORT}
      CONFIG_PATH: ${CONFIG_PATH}
    ports:
      - "${PARSER_SERVER_PORT}"
    networks:
      - backend
      - redis
    volumes:
      - uploads_data:/app/uploads

  redis:
    image: redis:latest
    container_name: redis-parser
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - redis

  master:
    build:
      context: ./master
      dockerfile: Dockerfile
    image: master:${MASTER_IMAGE_TAG}
    depends_on:
      - postgres
    container_name: master-server
    environment:
      MASTER_SERVER_PORT: ${MASTER_SERVER_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
      UPLOADS_DIR: ${UPLOADS_DIR}
    ports:
      - "${MASTER_SERVER_PORT}:${MASTER_SERVER_PORT}"
    networks:
      - backend
      - frontend
      - postgres
    volumes:
      - uploads_data:/app/uploads

  postgres:
    image: postgres:17
    container_name: postgres-master
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_URL: ${POSTGRES_URL}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - postgres

  client:
    build:
      context: ./client
      dockerfile: nginx/Dockerfile
    container_name: client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    networks:
      - frontend
    volumes:
      - uploads_data:/app/uploads

networks:
  backend:
  frontend:
  redis:
  postgres:

volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local
