services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: image_scraper
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./masterserver/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - backend

  masterserver:
    build:
      context: ./masterserver
      dockerfile: Dockerfile
    container_name: masterserver
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/image_scraper
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - backend
      - frontend


  parserserver:
    build:
      context: ./parseserver
      dockerfile: Dockerfile
    container_name: parseserver
    depends_on:
      - masterserver
    ports:
      - "8081:8081"
    networks:
      - backend

  client:
    build:
      context: ./client
      dockerfile: nginx/Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - frontend

networks:
  backend:
  frontend: